# Generated by Django 4.2.6 on 2023-10-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_id', models.CharField()),
                ('name', models.CharField()),
                ('bn_name', models.CharField()),
                ('lat', models.CharField()),
                ('long', models.CharField()),
            ],
        ),
    ]
